stages:  
 - test                        
 - build                         
 - deploy  
     
build_image: 
  stage : build
  image : docker
  services : 
    - name : docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script : 
    - docker -v
    - docker build -t rajaking786/reactjs:app .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push rajaking786/reactjs:app    


