stages:  
 - test                        
 - build                         
 - deploy  
     
build_image: 
  stage : build
  image : docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
  script : 
    - docker login registry.example.com -u $DOCKER_USERNAME -p glpat-Gy47zrfqHdMVHjh5fzmR
    - docker build -t raja786/docker-hello-world-spring-boot:demo-app-1.0
    - docker push raja786/docker-hello-world-spring-boot:demo-app-1.0  
    

