stages:  
 - test                        
 - build                         
 - deploy  
     
build_image:  
  stage : build
  image : maven:3.6-jdk-11
  script : 
    - mvn clean package -B
            
