stages:  
 - test                        
 - build                         
 - deploy  
     
build_image: 
  stage : build
  image : docker:20.10.16
  services:
    - docker:20.10.16-dind
  script : 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t  $CI_REGISTRY/rajaking786/hello-world .
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p glpat-Gy47zrfqHdMVHjh5fzmR
    - docker push $CI_REGISTRY/rajaking786/hello-world


