stages:  
 - test                        
 - build                         
 - deploy  
     
build_image: 
  stage : build
  image : docker:20.10.16
  services:
    - docker:20.10.16-dind
  script : 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login registry.gitlab.example.com -u $CI_REGISTRY_USER -p glpat-Gy47zrfqHdMVHjh5fzmR
    - docker build -t  /rajaking786/hello-world/myspring:latest .
    - docker push $CI_REGISTRY/rajaking786/hello-world/myspring:latest


