stages:  
 - test                        
 - build                         
 - deploy  

image: maven:3-jdk-11          

run_tests:
    before_script:
        - apt-get update && apt-get install make
    script: 
        -make test
                                 
maven-build:                                       
  script: "mvn package -B"       
