gstages:  
 - test                        
 - build                         
 - deploy  
     
build_image: 
  stage : build
  image : docker
  services : 
    - name : docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script : 
    - docker build -t rajaking786/springboot2:ICT .
    - docker login raja8193.jfrog.io -u $JFROG_USERNAME -p $JFROG_PASSWORD 
    


