stages:  
 - test                        
 - build                         
 - deploy  

run_tests:
    before_script:
        - apt-get update && apt-get install make
    script: 
        - make test
                                 
maven-build:                                       
  image: maven:3-jdk-11     
  script: "mvn package -B"       
