stages:  
 - test                        
 - build                         
 - deploy  
     
build_image:  
  stage : build
   script: 
      - docker build -t rajaking786/gitlab-demo:springboot-app-1.0
      - docker push  rajaking786/gitlab-demo:springboot-app-1.0
            
